### ISSUE TITLE
When creating / destroying multiple records it sometimes hangs on creation / destruction

### ISSUE THREAD

**Issue by rfranks-securenet** [PortOfPortland/terraform-provider-windns#11]
I have a terraform script that is creating four different classes of machines, with multiple in each class.

I have four different sections like this:

```
resource "windns" "dns_redis" {
  count  = var.vm_count_redis
  record_name   = "${var.vm_name_redis}-${element(random_id.vm_name_redis.*.hex, count.index)}"
  record_type = "A"
  zone_name = var.vm_domain
  ipv4address = element(phpipam_first_free_address.newip_redis, count.index).ip_address
}
```

Each section uses different variables for anywhere there is _redis (_logstash, etc.)

When I run it, creating six machines, it hangs on one of the creation. When I look in DNS, I can see it has created the record, but it never completes from Terraform's perspective, so it hangs there.

The same is true on destruction. It hangs on a single element, even though it has deleted it already. If I re-run the destroy, it errors with `Remove-DnsServerResourceRecord: Failed to get elk-logstash-fdf7b7 record`

Not sure what is causing it, but if I can do any more debug to help, let me know!

**Comment by rayterrill** [comment]
@rfranks-securenet Can you replicate this at will? Can you try it out with the --parallelism flag, and set it to 1 or something lower (https://www.terraform.io/docs/commands/apply.html#parallelism-n)?

I'm pretty sure I ran into this in our environment as well, and it was something to do with the amount of parallelism - shelling out and remoting into the downstream DNS server is such a hack, but unfortunately all we can really do with no API. :(

**Comment by rfranks-securenet** [comment]
I appreciate that shelling out and so on is a hack, but I've written some code to implement lockfiles which works around this issue, without having to run terraform with parallelism set low.

**Comment by rayterrill** [comment]
@rfranks-securenet I'll take a look. My fingers are crossed that Hashicorp will release an official WinDNS provider since they just released an AD provider, so I can sunset this one. :)

**Comment by rayterrill** [comment]
@rfranks-securenet release cut with your update! thanks mate!
