### ISSUE TITLE
Code applied, nothing happened

### ISSUE THREAD

**Issue by dcardellino** [PortOfPortland/terraform-provider-windns#16]
Hey there,

When i use this terraform provider to create a records for my server in Windows DNS, terraform code gets applied without errors, but when i check the dns server there are no records created.

I use the provider as following:
`provider "windns" {
  server = "mydns.domain.intern"
  username = "automationuser@domain.intern"
  password = "Sup3rS3cureP4ssw0rd"
  usessl = true
}
`
this is the resource to be created:
`
resource "windns" "arecord" {
  record_name = "test-record"
  record_type = "A"
  zone_name = "domain.intern"
  ipv4address = "10.1.180.1"
}
`

Am I using this provider wrong? The automation user has domain admin rights so it should be able to create records.
I am using this provider with terraform 0.13.4 on macos catalina.

**Comment by rayterrill** [comment]
@dcardellino Is this still an issue? Just pushed a new release with some bug fixes.

**Comment by rayterrill** [comment]
Closing - please re-open if still an issue.
