### ISSUE TITLE
On Linux: windns.dns: Could not spawn PowerShell process: exec: "powershell.exe"

### ISSUE THREAD

**Issue by archmangler** [PortOfPortland/terraform-provider-windns#3]
Running terraform on linux, it seems the windns provider is looking for powershell.exe, instead of pwsh which is the linux powershell.

- terraform plan is ok.
- terraform apply fails like:

```
                                                                                                            
Error: Error applying plan:                                                                                 
                                                                                                            
1 error(s) occurred:                                                                                        
                                                                                                            
* windns.dns: 1 error(s) occurred:                                                                          
                                                                                                            
* windns.dns: Could not spawn PowerShell process: exec: "powershell.exe": executable file not found in $PATH
                                                                                                            
Terraform does not automatically rollback in the face of errors.                                            
Instead, your Terraform state file has been partially updated with                                          
any resources that successfully completed. Please address the error                                         
above and apply again to incrementally change your infrastructure.                                          
                                                                                                            
```

How to configure the provider to automatically detect at build time (or runtime) which powershell interpreter to use?

**Comment by rayterrill** [comment]
This is actually a problem in the go-powershell module. It also looks like the company who wrote that deleted it. I'll try to take a look at this, but this looks fairly complicated.

**Comment by rayterrill** [comment]
@archmangler I just published a new release that's working for us on Linux. It currently only supports key based auth. I ended up ripping out the go-powershell module and writing another SUPER BASIC goPSRemoting module to shell out to Powershell or pwsh. There are some complexities with how this works currently from Linux to Windows. Let me know if you have a chance to test.

**Comment by nelsonyaccuzzi** [comment]
I can't get this to work on Linux, is something that I have to take into account? 

The terraform apply finish ok, but no DNS records are created.

**Comment by rayterrill** [comment]
@nelsonyaccuzzi Does something like this work from your linux machine?

```
$s = New-PSSession -HostName YOURSERVER -Username YOURUSERNAME -SSHTransport
Invoke-Command -Session $s -Scriptblock { Add-DNSServerResourceRecord -ZoneName ZONENAME -CNAME -Name TEST -IPv4Address 1.1.1.1 }
Remove-PSSession $s
```

**Comment by nelsonyaccuzzi** [comment]
I'm a bit lost here

How I am supposed to run Powershell commands from Linux?

**Comment by nelsonyaccuzzi** [comment]
Hi! I get it working without SSH

I needed to install this packages: epel-release, krb5-workstation, krb5-devel, gssntlmssp 

I modified the goPSremoting package to use the `-Authetication Negotiate` flag in non windows systems.

Mi env is a RHEL 7.6 and a Windows Server 2012 R2

**Comment by luboss79** [comment]
@nelsonyaccuzzi thanks for your advise to change the authentication method. It worked for me too.
The change is visible in my fork file https://github.com/luboss79/goPSRemoting/blob/master/main.go on line 44.

My env is Ubuntu 18.04 + Windows Server 2012 R2

For Ubuntu client, it was necessary to install the following packages:
`sudo apt install krb5-user libpam-krb5 libpam-ccreds auth-client-config gss-ntlmssp`

and then configure the krb:
`sudo dpkg-reconfigure krb5-config`

Hope will help others ;-)

**Comment by geraldnolan** [comment]
@luboss79 Thanks for posting this! Your changed worked perfectly for us with the same configuration.

**Comment by erSitzt** [comment]
could you provide a PR for your change @luboss79  ?

With the current state of code/documentation this provider is pretty much useless on linux...

btw. i didnt need `dpkg-reconfigure krb5-config` to user pwsh with `-Authentication negiotiate` @luboss79
