### ISSUE TITLE
Terraform-provider-DNS Wraps DNSServer Module but not installable on Linux

### ISSUE THREAD

**Issue by archmangler** [PortOfPortland/terraform-provider-windns#4]
terraform-provider-dns appears to wrap the DNSServer module. However this module doesn't appear to be installable on powershell on Linux, because it is not part of .Net Core.

Is there a specific procedure for installing DNSserver module for powershell on Linux?

**Comment by rayterrill** [comment]
@archmangler I doubt this will work on Linux given the current state of PowerShell Core. :(

**Comment by archmangler** [comment]
Apparently configuration of DNS on windows DNS server can be carried out from linux powershell via Powershell Remoting. If the Terraform provider could establish a PSSession to an MS Windows DNS server, it can execute a powershell script to configure DNS on that server (involving the DNSServer module).

**Comment by rayterrill** [comment]
@archmangler This might actually work then. That's exactly how this module works - it WinRMs into a DC to perform DNS operations. Honestly it's kind of a hack because MS doesn't provide a sensible way to do this kind of thing easily, but it mostly works for us.

I've been slammed at work lately on some issues. Hoping to have some time next week to take a crack at getting Linux support going.

**Comment by archmangler** [comment]
@rayterrill - I've tested the powershell remoting setup on linux to a windows 2016 server, the mechanism looks pretty stable. I'll try to look into a provider that uses this, but honestly, I've never tried to write one before, so if you manage to make one first I'll be glad to test it.

**Comment by rayterrill** [comment]
@archmangler I should be able to just compile this on Linux and let you give it a shot. Will try to get something working this week.

**Comment by archmangler** [comment]
Just a note, we may not even need ssh remoting configuration, just simply SSH, if the script can be copied over and executed in two steps as follows:

Copy:

```
scp -v addarecord.ps1 0101@winserver.lol.com:addarecord.ps1
```

Execute:

```
(.env) [0101@linuxserver terraform-implementation]$ ssh 0101@winserverlol.com 'powershell ./addarecord.ps1'
0101@winserverlol.com's password:

Add-DnsServerResourceRecordA : Cannot connect to CIM server. Access denied
At C:\Users\0101\addarecord.ps1:1 char:1
+ Add-DnsServerResourceRecordA -Name "testserver" -ZoneName
"testzone.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : ResourceUnavailable: (PS_DnsServerResourceRecord
   A:String) [Add-DnsServerResourceRecordA], CimJobException
    + FullyQualifiedErrorId : CimJob_BrokenCimSession,Add-DnsServerResourceRec
   ordA
```

**Comment by rayterrill** [comment]
@archmangler I updated the release https://github.com/PortOfPortland/terraform-provider-windns/releases/tag/v0.2.0 to include a Linux binary. See if that will work for you.

**Comment by rayterrill** [comment]
I'm gonna close this one. The actual issue is #3. The code here is actually correct, and should work, since it actually executes in the context of your DNS server.
