### ISSUE TITLE
Split configuration for WinRM Host and Domain Controller

### ISSUE THREAD

**Issue by estenrye** [PortOfPortland/terraform-provider-windns#5]
Hello,

First of all, thank you for this project, it has been a great tool for us to automate our DNS entries in AD.  One challenge we are facing with your provider is that the WinRM Host and the Domain Controller are expected to be the same host.  For security reasons, we do not allow WinRM connections directly to our Domain Controllers to all but the most privileged of users.

I plan on adding a pull request that maintains the existing functionality as is, but adds an additional provider configuration option to allow for connecting to a WinRM jump box and applying commands to a separate domain controller host.

Esten

**Comment by estenrye** [comment]
It looks like this is more difficult than I thought.  One of the drawbacks of the WinRM approach is that it runs into a second hop authentication problem that requires something like CredSSP to resolve.

https://blogs.technet.microsoft.com/askds/2012/08/02/windows-powershell-remoting-and-delegating-user-credentials/

I think for our environment we will probably remove the PS Remoting logic for our fork.

**Comment by rayterrill** [comment]
Hi @estenrye! So you'd like this to just call the code to handle the DNS side of things with PowerShell - without the remoting part? I think I might be able to pull that out.

The double-hop problem is exactly what we ran into, thus the remoting.

**Comment by rayterrill** [comment]
@estenrye I'm going to close this for now - let me know if there is something else I can do.
